### ISSUE TITLE
[BUG] ValueError: Invalid URL

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/mobility-database-interface#205]
[Error report](https://console.cloud.google.com/errors/CMbmk4Cr6vHnfw?time=P7D&refresh=auto&project=top-glass-307718)

```python
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/functions_framework/__init__.py", line 149, in view_func
    function(data, context)
  File "/workspace/main.py", line 74, in add_new_source_cf
    source_entity_id = add_source_and_dispatch(
  File "/workspace/helpers_cf.py", line 229, in add_source_and_dispatch
    source_entity_id = add_source_in_db(source_name, stable_url, username, password)
  File "/workspace/helpers_cf.py", line 195, in add_source_in_db
    source_stable_url = wbi_core.Url(value=stable_url, prop_nr=stable_url_prop)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/wikibaseintegrator/wbi_core.py", line 2230, in __init__
    self.set_value(value)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/wikibaseintegrator/wbi_core.py", line 2236, in set_value
    raise ValueError('Invalid URL')
ValueError: Invalid URL
```

**Comment by maximearmstrong** [comment]
Outdated, already fixed.
